name: Automatic service version bump

on:
  push:
    branches:
      - develop

jobs:
  call-service-version-bump-workflow:
    uses: PhraseePhoundry/ga-workflows/.github/workflows/service-versioning.yml@develop
    secrets:
      JiraUrl: ${{ secrets.JIRA_BASE_URL }}
      JiraApiToken: ${{ secrets.JIRA_API_TOKEN }}
      JiraEmail: ${{ secrets.JIRA_USER_EMAIL }}