name: Automatic service version bump

on:
  push:
    branches:
      - develop

jobs:
  call-service-version-bump-workflow:
    uses: PhraseePhoundry/ga-workflows/.github/workflows/service-versioning.yml@develop