
name: Automatic service versioning and Jira update

on:
  push:
    branches:
      - main

jobs:
  bump-service-version:
    name: Bump service version
    runs-on: ubuntu-latest
    outputs:
      newTag: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: cat package.json
        run: cat ./package.json

      - name: Bump version
        id: version-bump
        uses: PhraseePhoundry/gh-action-bump-version/.github/actions/bump-version@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  update-jira-ticket:
    name: Update Jira ticket
    runs-on: ubuntu-latest
    needs: bump-service-version

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Jira login
        uses: PhraseePhoundry/ga-jira-login@main
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find issue key
        id: find-issue-key
        uses: PhraseePhoundry/ga-jira-find-issue-key@main
        with:
          from: commits
      
      - name: Update Jira issue
        uses: PhraseePhoundry/ga-jira-update-issue@main
        with:
          issue: ${{ steps.find-issue-key.outputs.issue }}
          newTag: ${{ needs.bump-service-version.outputs.newTag }}
