
name: Automatic service version bump

on:
  workflow_call:

jobs:
  bump-service-version:
    name: Bump service version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Run git fetch
        run: git fetch --prune --unshallow
      
      - name: Get latest git tag
        id: get-latest-tag
        uses: PhraseePhoundry/ga-get-current-tag@main
        with:
          fallback: '1.0.0'

      - name: Bump version
        id: version-bump
        uses: PhraseePhoundry/gh-action-bump-version/.github/actions/bump-version@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_TAG: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Output Step
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
